# Use the official Nginx image as a base
FROM nginx

# Copy the contents of the public folder to the default Nginx public directory
COPY ./public /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80